### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [lukasbestle/kirby-downloads#2]
> The installed version of the Kirby Downloads plugin is not compatible with Kirby 4.0.0-rc.4

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by lukasbestle** [comment]
For everyone reading along: I will update my plugins for Kirby 4 in the next few days. 🙂

**Comment by lukasbestle** [comment]
Due to a bug in Kirby 4 (https://github.com/getkirby/kirby/pull/6181), an updated release for this plugin will have to wait until Kirby 4.1.0. I'll prepare everything in the meantime.
