### ISSUE TITLE
Remove preselection-note if no fields/filters are specified

### ISSUE THREAD

**Issue by twiro** [lukasbestle/kirby-downloads#3]
I am using the downloads-block in a minimal setting **without any fields & filters**, and while this basically works as expected it would be nice if the **preselection-note** would not be shown at all in this scenario as it simply makes no sense when all you can do is manually select some files:

## Screenshot

<img width="800" alt="Bildschirmfoto 2024-06-27 um 20 39 45" src="https://github.com/lukasbestle/kirby-downloads/assets/870227/cfb57d18-cf8f-4f68-9533-6cab30fb9c78">

## Technical details

- Plugin version: 1.1.0
- Kirby version: 4.3.0

**Comment by lukasbestle** [comment]
With the new `search` option (see #4) I've implemented it so that the info box is hidden together with the Interface tab.
