### ISSUE TITLE
Configuration option to remove the "Interface"-tab

### ISSUE THREAD

**Issue by twiro** [lukasbestle/kirby-downloads#4]
## Is your feature request related to a problem? Please describe.

In my scenario I'd like the editors to only use the downloads block for selecting (and sorting) a bunch of files to generate a simple download list inbetween other content blocks – no filters, no search, no nothing.

Right now I can't get rid of the interface tab and the search option which causes confusion as the result in the frontend should be a simple list of downloads without any interface/interaction.

## Solution you'd like

A configuration option that would allow to remove the "Interface"-tab would be great.

```
return [
  'lukasbestle.downloads' => [
    'path' => 'downloads',
    'fields' => null, 
    'paginate' => null,
    'template' => null,
    'interface' => false,
  ]
];
```

**Comment by lukasbestle** [comment]
I've implemented a new `search` option. If both `fields` and `search` are disabled, the Interface tab is hidden automatically.
